from mpyzeebe.exceptions.pyzeebe_exceptions import PyZeebeException


class MessageAlreadyExists(PyZeebeException):
    pass
